---

- name: Gather EC2 instance metadata
  action: ec2_metadata_facts

- name: Obtain EC2 tags for this instance
  local_action:
    module: ec2_tag
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ ansible_ec2_instance_id }}"
    state: list
  register: ec2_tags


- name: "Configure zabbix-agent"
  template: 
     src: zabbix_agentd.conf.j2
     dest: "{{ zabbix_agent_dir_etc }}/zabbix_agentd.conf" 
     owner: root
     group: "{{ zabbix_agent_user }}"
     mode: 0640
  notify:
    - restart zabbix-agent

- name: "Creates '/etc/zabbix/script' directory"  
  file:
    path: /etc/zabbix/script
    state: directory
    owner: root
    group: "{{ zabbix_agent_user }}"
    mode: 0640

- name: "Copy CIS scripts"
  template:
    src: "{{ item }}"
    dest: /etc/zabbix/script/{{ item }}
    owner: root
    group: "{{ zabbix_agent_user }}"
    mode: 0640
  with_items:
    - "{{ cis_scripts }}"

- name: "Configure agent for CIS"
  template:
     src: userparam_cis.conf.j2
     dest: "{{ zabbix_agent_dir_etc }}/zabbix_agentd.d/userparam_cis.conf"
     owner: root
     group: "{{ zabbix_agent_user }}"
     mode: 0640
  notify:
    - restart zabbix-agent
