---
- name: "Installing repository gpg"
  rpm_key:
     state: present
     key: "{{ zabbix_rpmgpgkey }}"

- name: "Installing repository rpm"
  yum: 
     pkg: "{{ item }}"
     state: present 
  with_items:
    - "{{ zabbix_repository }}"

- name: "Update zabbix"
  yum: 
     name: zabbix-agent
     state: latest
     update_cache: yes
  notify:
    - restart zabbix-agent

- name: "Ensure zabbix-agent started/stopped"
  service: 
     name: "{{ zabbix_agent_service }}"
     state: "{{ zabbix_agent_service_state }}" 
     enabled: "{{ zabbix_agent_service_enabled }}"
