---
- name: "installing repository gpg"
  action: rpm_key state=present key=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX

- name: "installing repository rpm (redhat)"
  action: yum pkg={{item}} state=installed
  with_items:
  - http://repo.zabbix.com/zabbix/3.2/rhel/6/x86_64/zabbix-release-3.2-1.el6.noarch.rpm

- name: update zabbix
  yum: name=zabbix-agent state=latest
  notify:
  - restart zabbix-agent

- name: Ensure zabbix-agent started/stopped
  service: name={{ zabbix_agent_service }} state={{ zabbix_agent_service_state }} enabled={{ zabbix_agent_service_enabled }}

